#!/usr/bin/env python3
"""
gen_wallpaper.py — SQ-OS Wallpaper Generator
=============================================
Generates assets/wallpaper_data.h containing a 320x200 VGA palette pixel
array for the SQ-OS desktop background.

Usage:
  python assets/gen_wallpaper.py

Output:
  assets/wallpaper_data.h   — const uint8_t wallpaper_data[64000]

The wallpaper uses the standard VGA 256-colour palette (mode 13h default).
We generate a retro teal-to-navy diagonal gradient with a subtle scanline
dithering effect, giving a classic Windows 3.x / OS/2 feel.

VGA palette colour indices used (mode 13h default palette):
  1  = Dark blue (navy)
  3  = Dark cyan / teal
  9  = Bright blue
  11 = Bright cyan
"""

import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_PATH   = os.path.join(SCRIPT_DIR, "wallpaper_data.h")

WIDTH  = 320
HEIGHT = 200

def vga_wallpaper_pixel(x, y):
    """
    Retro diagonal gradient wallpaper.
    Top-left: navy (colour 1)  →  Bottom-right: teal (colour 3)
    Odd scanlines are slightly darkened for a subtle CRT scanline effect.
    """
    # Normalised diagonal value 0..255
    diag = (x * 2 + y * 3) % 256

    # Base colour: cycle between navy(1) → dark cyan(3) → blue(9)
    if diag < 80:
        base = 1   # navy
    elif diag < 160:
        base = 3   # teal / dark cyan
    else:
        base = 9   # bright blue

    # Subtle scanline dither: darken every other row slightly
    if (y & 1) == 1 and diag < 80:
        base = 1   # keep navy on dark rows

    # Starfield: sprinkle white dots at pseudo-random positions
    # Use a simple LCG hash to place ~180 stars across the desktop area
    h = (x * 0xAB4F + y * 0x4321 + x * y) & 0xFFFFFFFF
    if (h % 350) == 0 and y > 10 and y < 190:
        base = 15  # white

    # Bright accent band near top (subtle horizon line effect)
    if y == 10 or y == 11:
        base = 11  # bright cyan — top-bar separator glow

    return base


def main():
    pixels = []
    for y in range(HEIGHT):
        for x in range(WIDTH):
            pixels.append(vga_wallpaper_pixel(x, y))

    assert len(pixels) == WIDTH * HEIGHT == 64000

    lines = [
        "/* wallpaper_data.h — Auto-generated by assets/gen_wallpaper.py",
        " * DO NOT EDIT MANUALLY.",
        " * 320x200 VGA mode-13h pixel array (64 000 bytes, 8-bit palette indices). */",
        "#ifndef WALLPAPER_DATA_H",
        "#define WALLPAPER_DATA_H",
        "",
        "#include <stdint.h>",
        "",
        "static const uint8_t wallpaper_data[64000] = {",
    ]

    # Emit 16 bytes per source line for compact output
    for i in range(0, len(pixels), 16):
        chunk = pixels[i:i+16]
        line  = "    " + ", ".join(f"0x{b:02X}" for b in chunk) + ","
        lines.append(line)

    lines += [
        "};",
        "",
        "#endif /* WALLPAPER_DATA_H */",
        "",
    ]

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))

    print(f"[gen_wallpaper] Written {len(pixels)} pixels -> {OUT_PATH}")


if __name__ == "__main__":
    main()
